; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\cygwin\home\Student\so-labs\lab1\examples\hello.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG2638	DB	'SO, ... hello world!', 0aH, 00H
_DATA	ENDS
PUBLIC	_main
EXTRN	_printf:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File c:\cygwin\home\student\so-labs\lab1\examples\hello.c
; Line 4
	push	ebp
	mov	ebp, esp
; Line 5
	push	OFFSET $SG2638
	call	_printf
	add	esp, 4
; Line 7
	xor	eax, eax
; Line 8
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
