CFLAGS=/nologo /W4 /EHsc /Za /DDEBUG__=1
CC = cl

main.exe: main.obj add.obj
	$(CC) $(CFLAGS) /Fe$@ $**
main.obj: main.c
	$(CC) $(CFLAGS) /c $**
add.obj: add.c
	$(CC) $(CFLAGS) /c $**
clean:
	del *.obj *.exe
